import type { PrefectureInfo } from './types.js';

// 隣接情報: https://www.mlit.go.jp/tec/content/001708606.pdf
// (同様の資料 https://www.mlit.go.jp/tec/nyuusatu/hattyu/rinsetu.pdf には誤りがあるので注意)
export const prefectureInfos: readonly PrefectureInfo[] = [
    {
        id: 'hokkaido',
        name: '北海道',
        shortName: '北海道',
        website: 'https://www.pref.hokkaido.lg.jp/',
        adjacentPrefectureIds: ['aomori'],
    },
    {
        id: 'aomori',
        name: '青森県',
        shortName: '青森',
        website: 'https://www.pref.aomori.lg.jp/',
        adjacentPrefectureIds: ['hokkaido', 'iwate', 'akita'],
    },
    {
        id: 'iwate',
        name: '岩手県',
        shortName: '岩手',
        website: 'https://www.pref.iwate.jp/',
        adjacentPrefectureIds: ['aomori', 'miyagi', 'akita'],
    },
    {
        id: 'miyagi',
        name: '宮城県',
        shortName: '宮城',
        website: 'https://www.pref.miyagi.jp/',
        adjacentPrefectureIds: ['iwate', 'akita', 'yamagata', 'fukushima'],
    },
    {
        id: 'akita',
        name: '秋田県',
        shortName: '秋田',
        website: 'https://www.pref.akita.lg.jp/',
        adjacentPrefectureIds: ['aomori', 'iwate', 'miyagi', 'yamagata'],
    },
    {
        id: 'yamagata',
        name: '山形県',
        shortName: '山形',
        website: 'https://www.pref.yamagata.jp/',
        adjacentPrefectureIds: ['miyagi', 'akita', 'fukushima', 'niigata'],
    },
    {
        id: 'fukushima',
        name: '福島県',
        shortName: '福島',
        website: 'https://www.pref.fukushima.lg.jp/',
        adjacentPrefectureIds: [
            'miyagi',
            'yamagata',
            'ibaraki',
            'tochigi',
            'gunma',
            'niigata',
        ],
    },
    {
        id: 'ibaraki',
        name: '茨城県',
        shortName: '茨城',
        website: 'https://www.pref.ibaraki.jp/',
        adjacentPrefectureIds: ['fukushima', 'tochigi', 'saitama', 'chiba'],
    },
    {
        id: 'tochigi',
        name: '栃木県',
        shortName: '栃木',
        website: 'https://www.pref.tochigi.lg.jp/',
        adjacentPrefectureIds: ['fukushima', 'ibaraki', 'gunma', 'saitama'],
    },
    {
        id: 'gunma',
        name: '群馬県',
        shortName: '群馬',
        website: 'https://www.pref.gunma.jp/',
        adjacentPrefectureIds: [
            'fukushima',
            'tochigi',
            'saitama',
            'niigata',
            'nagano',
        ],
    },
    {
        id: 'saitama',
        name: '埼玉県',
        shortName: '埼玉',
        website: 'https://www.pref.saitama.lg.jp/',
        adjacentPrefectureIds: [
            'ibaraki',
            'tochigi',
            'gunma',
            'chiba',
            'tokyo',
            'yamanashi',
            'nagano',
        ],
    },
    {
        id: 'chiba',
        name: '千葉県',
        shortName: '千葉',
        website: 'https://www.pref.chiba.lg.jp/',
        adjacentPrefectureIds: ['ibaraki', 'saitama', 'tokyo', 'kanagawa'],
    },
    {
        id: 'tokyo',
        name: '東京都',
        shortName: '東京',
        website: 'https://www.metro.tokyo.lg.jp/',
        adjacentPrefectureIds: ['saitama', 'chiba', 'kanagawa', 'yamanashi'],
    },
    {
        id: 'kanagawa',
        name: '神奈川県',
        shortName: '神奈川',
        website: 'https://www.pref.kanagawa.jp/',
        adjacentPrefectureIds: ['chiba', 'tokyo', 'yamanashi', 'shizuoka'],
    },
    {
        id: 'niigata',
        name: '新潟県',
        shortName: '新潟',
        website: 'https://www.pref.niigata.lg.jp/',
        adjacentPrefectureIds: [
            'yamagata',
            'fukushima',
            'gunma',
            'toyama',
            'nagano',
        ],
    },
    {
        id: 'toyama',
        name: '富山県',
        shortName: '富山',
        website: 'https://www.pref.toyama.jp/',
        adjacentPrefectureIds: ['niigata', 'ishikawa', 'nagano', 'gifu'],
    },
    {
        id: 'ishikawa',
        name: '石川県',
        shortName: '石川',
        website: 'https://www.pref.ishikawa.lg.jp/',
        adjacentPrefectureIds: ['toyama', 'fukui', 'gifu'],
    },
    {
        id: 'fukui',
        name: '福井県',
        shortName: '福井',
        website: 'https://www.pref.fukui.lg.jp/',
        adjacentPrefectureIds: ['ishikawa', 'gifu', 'shiga', 'kyoto'],
    },
    {
        id: 'yamanashi',
        name: '山梨県',
        shortName: '山梨',
        website: 'https://www.pref.yamanashi.jp/',
        adjacentPrefectureIds: [
            'saitama',
            'tokyo',
            'kanagawa',
            'nagano',
            'shizuoka',
        ],
    },
    {
        id: 'nagano',
        name: '長野県',
        shortName: '長野',
        website: 'https://www.pref.nagano.lg.jp/',
        adjacentPrefectureIds: [
            'gunma',
            'saitama',
            'niigata',
            'toyama',
            'yamanashi',
            'gifu',
            'shizuoka',
            'aichi',
        ],
    },
    {
        id: 'gifu',
        name: '岐阜県',
        shortName: '岐阜',
        website: 'https://www.pref.gifu.lg.jp/',
        adjacentPrefectureIds: [
            'toyama',
            'ishikawa',
            'fukui',
            'nagano',
            'aichi',
            'mie',
            'shiga',
        ],
    },
    {
        id: 'shizuoka',
        name: '静岡県',
        shortName: '静岡',
        website: 'https://www.pref.shizuoka.jp/',
        adjacentPrefectureIds: ['kanagawa', 'yamanashi', 'nagano', 'aichi'],
    },
    {
        id: 'aichi',
        name: '愛知県',
        shortName: '愛知',
        website: 'https://www.pref.aichi.jp/',
        adjacentPrefectureIds: ['nagano', 'gifu', 'shizuoka', 'mie'],
    },
    {
        id: 'mie',
        name: '三重県',
        shortName: '三重',
        website: 'https://www.pref.mie.lg.jp/',
        adjacentPrefectureIds: [
            'gifu',
            'aichi',
            'shizuoka',
            'kyoto',
            'nara',
            'wakayama',
        ],
    },
    {
        id: 'shiga',
        name: '滋賀県',
        shortName: '滋賀',
        website: 'https://www.pref.shiga.lg.jp/',
        adjacentPrefectureIds: ['fukui', 'gifu', 'mie', 'kyoto'],
    },
    {
        id: 'kyoto',
        name: '京都府',
        shortName: '京都',
        website: 'https://www.pref.kyoto.jp/',
        adjacentPrefectureIds: [
            'fukui',
            'mie',
            'shiga',
            'osaka',
            'hyogo',
            'nara',
        ],
    },
    {
        id: 'osaka',
        name: '大阪府',
        shortName: '大阪',
        website: 'https://www.pref.osaka.lg.jp/',
        adjacentPrefectureIds: ['kyoto', 'hyogo', 'nara', 'wakayama'],
    },
    {
        id: 'hyogo',
        name: '兵庫県',
        shortName: '兵庫',
        website: 'https://web.pref.hyogo.lg.jp/',
        adjacentPrefectureIds: [
            'kyoto',
            'osaka',
            'tottori',
            'okayama',
            'tokushima',
        ],
    },
    {
        id: 'nara',
        name: '奈良県',
        shortName: '奈良',
        website: 'https://www.pref.nara.jp/',
        adjacentPrefectureIds: ['mie', 'kyoto', 'osaka', 'wakayama'],
    },
    {
        id: 'wakayama',
        name: '和歌山県',
        shortName: '和歌山',
        website: 'https://www.pref.wakayama.lg.jp/',
        adjacentPrefectureIds: ['mie', 'osaka', 'nara'],
    },
    {
        id: 'tottori',
        name: '鳥取県',
        shortName: '鳥取',
        website: 'https://www.pref.tottori.lg.jp/',
        adjacentPrefectureIds: ['hyogo', 'shimane', 'okayama', 'hiroshima'],
    },
    {
        id: 'shimane',
        name: '島根県',
        shortName: '島根',
        website: 'https://www.pref.shimane.lg.jp/',
        adjacentPrefectureIds: ['tottori', 'hiroshima', 'yamaguchi'],
    },
    {
        // 国土交通省の一部の文書では鳥取県が島根県と間違えられている
        id: 'okayama',
        name: '岡山県',
        shortName: '岡山',
        website: 'https://www.pref.okayama.jp/',
        adjacentPrefectureIds: [
            'hyogo',
            'tottori',
            'shimane',
            'hiroshima',
            'kagawa',
        ],
    },
    {
        id: 'hiroshima',
        name: '広島県',
        shortName: '広島',
        website: 'https://www.pref.hiroshima.lg.jp/',
        adjacentPrefectureIds: [
            'tottori',
            'shimane',
            'okayama',
            'yamaguchi',
            'ehime',
        ],
    },
    {
        id: 'yamaguchi',
        name: '山口県',
        shortName: '山口',
        website: 'https://www.pref.yamaguchi.lg.jp/',
        adjacentPrefectureIds: ['shimane', 'hiroshima', 'fukuoka'],
    },
    {
        id: 'tokushima',
        name: '徳島県',
        shortName: '徳島',
        website: 'https://www.pref.tokushima.lg.jp/',
        adjacentPrefectureIds: ['hyogo', 'kagawa', 'ehime', 'kochi'],
    },
    {
        id: 'kagawa',
        name: '香川県',
        shortName: '香川',
        website: 'https://www.pref.kagawa.lg.jp/',
        adjacentPrefectureIds: ['okayama', 'tokushima', 'ehime'],
    },
    {
        id: 'ehime',
        name: '愛媛県',
        shortName: '愛媛',
        website: 'https://www.pref.ehime.jp/',
        adjacentPrefectureIds: ['hiroshima', 'tokushima', 'kagawa', 'kochi'],
    },
    {
        id: 'kochi',
        name: '高知県',
        shortName: '高知',
        website: 'https://www.pref.kochi.lg.jp/',
        adjacentPrefectureIds: ['tokushima', 'ehime'],
    },
    {
        id: 'fukuoka',
        name: '福岡県',
        shortName: '福岡',
        website: 'https://www.pref.fukuoka.lg.jp/',
        adjacentPrefectureIds: ['yamaguchi', 'saga', 'kumamoto', 'oita'],
    },
    {
        id: 'saga',
        name: '佐賀県',
        shortName: '佐賀',
        website: 'https://www.pref.saga.lg.jp/',
        adjacentPrefectureIds: ['fukuoka', 'nagasaki'],
    },
    {
        id: 'nagasaki',
        name: '長崎県',
        shortName: '長崎',
        website: 'https://www.pref.nagasaki.jp/',
        adjacentPrefectureIds: ['saga'],
    },
    {
        id: 'kumamoto',
        name: '熊本県',
        shortName: '熊本',
        website: 'https://www.pref.kumamoto.jp/',
        adjacentPrefectureIds: ['fukuoka', 'oita', 'miyazaki', 'kagoshima'],
    },
    {
        id: 'oita',
        name: '大分県',
        shortName: '大分',
        website: 'https://www.pref.oita.jp/',
        adjacentPrefectureIds: ['fukuoka', 'kumamoto', 'miyazaki'],
    },
    {
        id: 'miyazaki',
        name: '宮崎県',
        shortName: '宮崎',
        website: 'https://www.pref.miyazaki.lg.jp/',
        adjacentPrefectureIds: ['kumamoto', 'oita', 'kagoshima'],
    },
    {
        id: 'kagoshima',
        name: '鹿児島県',
        shortName: '鹿児島',
        website: 'https://www.pref.kagoshima.jp/',
        adjacentPrefectureIds: ['kumamoto', 'miyazaki'],
    },
    {
        id: 'okinawa',
        name: '沖縄県',
        shortName: '沖縄',
        website: 'https://www.pref.okinawa.jp/',
        adjacentPrefectureIds: [],
    },
];
