export type PrefectureId =
    | 'hokkaido'
    | 'aomori'
    | 'iwate'
    | 'miyagi'
    | 'akita'
    | 'yamagata'
    | 'fukushima'
    | 'ibaraki'
    | 'tochigi'
    | 'gunma'
    | 'saitama'
    | 'chiba'
    | 'tokyo'
    | 'kanagawa'
    | 'niigata'
    | 'toyama'
    | 'ishikawa'
    | 'fukui'
    | 'yamanashi'
    | 'nagano'
    | 'gifu'
    | 'shizuoka'
    | 'aichi'
    | 'mie'
    | 'shiga'
    | 'kyoto'
    | 'osaka'
    | 'hyogo'
    | 'nara'
    | 'wakayama'
    | 'tottori'
    | 'shimane'
    | 'okayama'
    | 'hiroshima'
    | 'yamaguchi'
    | 'tokushima'
    | 'kagawa'
    | 'ehime'
    | 'kochi'
    | 'fukuoka'
    | 'saga'
    | 'nagasaki'
    | 'kumamoto'
    | 'oita'
    | 'miyazaki'
    | 'kagoshima'
    | 'okinawa';

export interface PrefectureInfo {
    id: PrefectureId;
    name: string;
    shortName: string;
    website: string;
    adjacentPrefectureIds: readonly PrefectureId[];
}
