export const sanDistrictIds2015 = [
    'hokkaido',
    'aomori',
    'iwate',
    'miyagi',
    'akita',
    'yamagata',
    'fukushima',
    'ibaraki',
    'tochigi',
    'gunma',
    'saitama',
    'chiba',
    'tokyo',
    'kanagawa',
    'niigata',
    'toyama',
    'ishikawa',
    'fukui',
    'yamanashi',
    'nagano',
    'gifu',
    'shizuoka',
    'aichi',
    'mie',
    'shiga',
    'kyoto',
    'osaka',
    'hyogo',
    'nara',
    'wakayama',
    'tottori-shimane',
    'okayama',
    'hiroshima',
    'yamaguchi',
    'tokushima-kochi',
    'kagawa',
    'ehime',
    'fukuoka',
    'saga',
    'nagasaki',
    'kumamoto',
    'oita',
    'miyazaki',
    'kagoshima',
    'okinawa',
] as const;

export type SanDistrictId2015 = (typeof sanDistrictIds2015)[number];

export interface SanDistrict2015 {
    id: SanDistrictId2015;
    name: string;
    seats: number;
}

export const sanDistricts2015: readonly SanDistrict2015[] = [
    { id: 'hokkaido', name: '北海道', seats: 3 },
    { id: 'aomori', name: '青森県', seats: 1 },
    { id: 'iwate', name: '岩手県', seats: 1 },
    { id: 'miyagi', name: '宮城県', seats: 1 },
    { id: 'akita', name: '秋田県', seats: 1 },
    { id: 'yamagata', name: '山形県', seats: 1 },
    { id: 'fukushima', name: '福島県', seats: 1 },
    { id: 'ibaraki', name: '茨城県', seats: 2 },
    { id: 'tochigi', name: '栃木県', seats: 1 },
    { id: 'gunma', name: '群馬県', seats: 1 },
    { id: 'saitama', name: '埼玉県', seats: 4 },
    { id: 'chiba', name: '千葉県', seats: 3 },
    { id: 'tokyo', name: '東京都', seats: 6 },
    { id: 'kanagawa', name: '神奈川県', seats: 4 },
    { id: 'niigata', name: '新潟県', seats: 1 },
    { id: 'toyama', name: '富山県', seats: 1 },
    { id: 'ishikawa', name: '石川県', seats: 1 },
    { id: 'fukui', name: '福井県', seats: 1 },
    { id: 'yamanashi', name: '山梨県', seats: 1 },
    { id: 'nagano', name: '長野県', seats: 1 },
    { id: 'gifu', name: '岐阜県', seats: 1 },
    { id: 'shizuoka', name: '静岡県', seats: 2 },
    { id: 'aichi', name: '愛知県', seats: 4 },
    { id: 'mie', name: '三重県', seats: 1 },
    { id: 'shiga', name: '滋賀県', seats: 1 },
    { id: 'kyoto', name: '京都府', seats: 2 },
    { id: 'osaka', name: '大阪府', seats: 4 },
    { id: 'hyogo', name: '兵庫県', seats: 3 },
    { id: 'nara', name: '奈良県', seats: 1 },
    { id: 'wakayama', name: '和歌山県', seats: 1 },
    { id: 'tottori-shimane', name: '鳥取県・島根県', seats: 1 },
    { id: 'okayama', name: '岡山県', seats: 1 },
    { id: 'hiroshima', name: '広島県', seats: 2 },
    { id: 'yamaguchi', name: '山口県', seats: 1 },
    { id: 'tokushima-kochi', name: '徳島県・高知県', seats: 1 },
    { id: 'kagawa', name: '香川県', seats: 1 },
    { id: 'ehime', name: '愛媛県', seats: 1 },
    { id: 'fukuoka', name: '福岡県', seats: 3 },
    { id: 'saga', name: '佐賀県', seats: 1 },
    { id: 'nagasaki', name: '長崎県', seats: 1 },
    { id: 'kumamoto', name: '熊本県', seats: 1 },
    { id: 'oita', name: '大分県', seats: 1 },
    { id: 'miyazaki', name: '宮崎県', seats: 1 },
    { id: 'kagoshima', name: '鹿児島県', seats: 1 },
    { id: 'okinawa', name: '沖縄県', seats: 1 },
];
