export const prefectureNames = [
    '北海道',
    '青森県',
    '岩手県',
    '宮城県',
    '秋田県',
    '山形県',
    '福島県',
    '茨城県',
    '栃木県',
    '群馬県',
    '埼玉県',
    '千葉県',
    '東京都',
    '神奈川県',
    '新潟県',
    '富山県',
    '石川県',
    '福井県',
    '山梨県',
    '長野県',
    '岐阜県',
    '静岡県',
    '愛知県',
    '三重県',
    '滋賀県',
    '京都府',
    '大阪府',
    '兵庫県',
    '奈良県',
    '和歌山県',
    '鳥取県',
    '島根県',
    '岡山県',
    '広島県',
    '山口県',
    '徳島県',
    '香川県',
    '愛媛県',
    '高知県',
    '福岡県',
    '佐賀県',
    '長崎県',
    '熊本県',
    '大分県',
    '宮崎県',
    '鹿児島県',
    '沖縄県',
] as const;

export const prefectureNamesWithoutSuffix = [
    '北海道',
    '青森',
    '岩手',
    '宮城',
    '秋田',
    '山形',
    '福島',
    '茨城',
    '栃木',
    '群馬',
    '埼玉',
    '千葉',
    '東京',
    '神奈川',
    '新潟',
    '富山',
    '石川',
    '福井',
    '山梨',
    '長野',
    '岐阜',
    '静岡',
    '愛知',
    '三重',
    '滋賀',
    '京都',
    '大阪',
    '兵庫',
    '奈良',
    '和歌山',
    '鳥取',
    '島根',
    '岡山',
    '広島',
    '山口',
    '徳島',
    '香川',
    '愛媛',
    '高知',
    '福岡',
    '佐賀',
    '長崎',
    '熊本',
    '大分',
    '宮崎',
    '鹿児島',
    '沖縄',
] as const;

export const prefectureIds = [
    'hokkaido',
    'aomori',
    'iwate',
    'miyagi',
    'akita',
    'yamagata',
    'fukushima',
    'ibaraki',
    'tochigi',
    'gunma',
    'saitama',
    'chiba',
    'tokyo',
    'kanagawa',
    'niigata',
    'toyama',
    'ishikawa',
    'fukui',
    'yamanashi',
    'nagano',
    'gifu',
    'shizuoka',
    'aichi',
    'mie',
    'shiga',
    'kyoto',
    'osaka',
    'hyogo',
    'nara',
    'wakayama',
    'tottori',
    'shimane',
    'okayama',
    'hiroshima',
    'yamaguchi',
    'tokushima',
    'kagawa',
    'ehime',
    'kochi',
    'fukuoka',
    'saga',
    'nagasaki',
    'kumamoto',
    'oita',
    'miyazaki',
    'kagoshima',
    'okinawa',
] as const;

type PrefectureName = typeof prefectureNames[number];
type PrefectureNameWithoutSuffix = typeof prefectureNamesWithoutSuffix[number];
export type PrefectureId = typeof prefectureIds[number];

export const prefecturalWebsites: { [key in PrefectureId]: string } = {
    hokkaido: 'https://www.pref.hokkaido.lg.jp/',
    aomori: 'https://www.pref.aomori.lg.jp/',
    iwate: 'https://www.pref.iwate.jp/',
    miyagi: 'https://www.pref.miyagi.jp/',
    akita: 'https://www.pref.akita.lg.jp/',
    yamagata: 'https://www.pref.yamagata.jp/',
    fukushima: 'https://www.pref.fukushima.lg.jp/',
    ibaraki: 'https://www.pref.ibaraki.jp/',
    tochigi: 'https://www.pref.tochigi.lg.jp/',
    gunma: 'https://www.pref.gunma.jp/',
    saitama: 'https://www.pref.saitama.lg.jp/',
    chiba: 'https://www.pref.chiba.lg.jp/',
    tokyo: 'https://www.metro.tokyo.lg.jp/',
    kanagawa: 'https://www.pref.kanagawa.jp/',
    niigata: 'https://www.pref.niigata.lg.jp/',
    toyama: 'https://www.pref.toyama.jp/',
    ishikawa: 'https://www.pref.ishikawa.lg.jp/',
    fukui: 'https://www.pref.fukui.lg.jp/',
    yamanashi: 'https://www.pref.yamanashi.jp/',
    nagano: 'https://www.pref.nagano.lg.jp/',
    gifu: 'https://www.pref.gifu.lg.jp/',
    shizuoka: 'https://www.pref.shizuoka.jp/',
    aichi: 'https://www.pref.aichi.jp/',
    mie: 'https://www.pref.mie.lg.jp/',
    shiga: 'https://www.pref.shiga.lg.jp/',
    kyoto: 'https://www.pref.kyoto.jp/',
    osaka: 'https://www.pref.osaka.lg.jp/',
    hyogo: 'https://web.pref.hyogo.lg.jp/',
    nara: 'https://www.pref.nara.jp/',
    wakayama: 'https://www.pref.wakayama.lg.jp/',
    tottori: 'https://www.pref.tottori.lg.jp/',
    shimane: 'https://www.pref.shimane.lg.jp/',
    okayama: 'https://www.pref.okayama.jp/',
    hiroshima: 'https://www.pref.hiroshima.lg.jp/',
    yamaguchi: 'https://www.pref.yamaguchi.lg.jp/',
    tokushima: 'https://www.pref.tokushima.lg.jp/',
    kagawa: 'https://www.pref.kagawa.lg.jp/',
    ehime: 'https://www.pref.ehime.jp/',
    kochi: 'https://www.pref.kochi.lg.jp/',
    fukuoka: 'https://www.pref.fukuoka.lg.jp/',
    saga: 'https://www.pref.saga.lg.jp/',
    nagasaki: 'https://www.pref.nagasaki.jp/',
    kumamoto: 'https://www.pref.kumamoto.jp/',
    oita: 'https://www.pref.oita.jp/',
    miyazaki: 'https://www.pref.miyazaki.lg.jp/',
    kagoshima: 'https://www.pref.kagoshima.jp/',
    okinawa: 'https://www.pref.okinawa.jp/',
};

// https://www.mlit.go.jp/tec/content/001708606.pdf
// (同様の資料 https://www.mlit.go.jp/tec/nyuusatu/hattyu/rinsetu.pdf には誤りがあるので注意)
export const adjacentPrefectures: { [key in PrefectureId]: PrefectureId[] } = {
    hokkaido: ['aomori'],
    aomori: ['hokkaido', 'iwate', 'akita'],
    iwate: ['aomori', 'miyagi', 'akita'],
    miyagi: ['iwate', 'akita', 'yamagata', 'fukushima'],
    akita: ['aomori', 'iwate', 'miyagi', 'yamagata'],
    yamagata: ['miyagi', 'akita', 'fukushima', 'niigata'],
    fukushima: ['miyagi', 'yamagata', 'ibaraki', 'tochigi', 'gunma', 'niigata'],
    ibaraki: ['fukushima', 'tochigi', 'saitama', 'chiba'],
    tochigi: ['fukushima', 'ibaraki', 'gunma', 'saitama'],
    gunma: ['fukushima', 'tochigi', 'saitama', 'niigata', 'nagano'],
    saitama: ['ibaraki', 'tochigi', 'gunma', 'chiba', 'tokyo', 'yamanashi', 'nagano'],
    chiba: ['ibaraki', 'saitama', 'tokyo', 'kanagawa'],
    tokyo: ['saitama', 'chiba', 'kanagawa', 'yamanashi'],
    kanagawa: ['chiba', 'tokyo', 'yamanashi', 'shizuoka'],
    niigata: ['yamagata', 'fukushima', 'gunma', 'toyama', 'nagano'],
    toyama: ['niigata', 'ishikawa', 'nagano', 'gifu'],
    ishikawa: ['toyama', 'fukui', 'gifu'],
    fukui: ['ishikawa', 'gifu', 'shiga', 'kyoto'],
    yamanashi: ['saitama', 'tokyo', 'kanagawa', 'nagano', 'shizuoka'],
    nagano: ['gunma', 'saitama', 'niigata', 'toyama', 'yamanashi', 'gifu', 'shizuoka', 'aichi'],
    gifu: ['toyama', 'ishikawa', 'fukui', 'nagano', 'aichi', 'mie', 'shiga'],
    shizuoka: ['kanagawa', 'yamanashi', 'nagano', 'aichi'],
    aichi: ['nagano', 'gifu', 'shizuoka', 'mie'],
    mie: ['gifu', 'aichi', 'shizuoka', 'kyoto', 'nara', 'wakayama'],
    shiga: ['fukui', 'gifu', 'mie', 'kyoto'],
    kyoto: ['fukui', 'mie', 'shiga', 'osaka', 'hyogo', 'nara'],
    osaka: ['kyoto', 'hyogo', 'nara', 'wakayama'],
    hyogo: ['kyoto', 'osaka', 'tottori', 'okayama', 'tokushima'],
    nara: ['mie', 'kyoto', 'osaka', 'wakayama'],
    wakayama: ['mie', 'osaka', 'nara'],
    tottori: ['hyogo', 'shimane', 'okayama', 'hiroshima'],
    shimane: ['tottori', 'hiroshima', 'yamaguchi'],
    // 国土交通省の一部の文書では次の行で、鳥取県が島根県と間違えられている
    okayama: ['hyogo', 'tottori', 'shimane', 'hiroshima', 'kagawa'],
    hiroshima: ['tottori', 'shimane', 'okayama', 'yamaguchi', 'ehime'],
    yamaguchi: ['shimane', 'hiroshima', 'fukuoka'],
    tokushima: ['hyogo', 'kagawa', 'ehime', 'kochi'],
    kagawa: ['okayama', 'tokushima', 'ehime'],
    ehime: ['hiroshima', 'tokushima', 'kagawa', 'kochi'],
    kochi: ['tokushima', 'ehime'],
    fukuoka: ['yamaguchi', 'saga', 'kumamoto', 'oita'],
    saga: ['fukuoka', 'nagasaki'],
    nagasaki: ['saga'],
    kumamoto: ['fukuoka', 'oita', 'miyazaki', 'kagoshima'],
    oita: ['fukuoka', 'kumamoto', 'miyazaki'],
    miyazaki: ['kumamoto', 'oita', 'kagoshima'],
    kagoshima: ['kumamoto', 'miyazaki'],
    okinawa: [],
};

export const getPrefectureName = (prefId: PrefectureId): PrefectureName => {
    const i = prefectureIds.indexOf(prefId);
    if (i === -1) throw new Error('No such prefecture id.');
    return prefectureNames[i];
};

export const getPrefectureId = (query: PrefectureName | PrefectureNameWithoutSuffix): PrefectureId => {
    const isWithSuffix = (query: string): query is PrefectureName => (
        prefectureNames.some(name => name === query)
    );
    const isWithoutSuffix = (query: string): query is PrefectureNameWithoutSuffix => (
        prefectureNamesWithoutSuffix.some(name => name === query)
    );
    if (isWithSuffix(query)) {
        return prefectureIds[prefectureNames.indexOf(query)];
    } else if (isWithoutSuffix(query)) {
        return prefectureIds[prefectureNamesWithoutSuffix.indexOf(query)];
    } else {
        throw new Error('Wrong prefecture name.');
    }
};
